# Generated by Django 3.0.7 on 2020-06-05 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200605_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type_',
            new_name='type',
        ),
    ]
