# Generated by Django 3.0.7 on 2020-06-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200605_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=5)),
                ('from_addr', models.CharField(max_length=128)),
                ('to_addr', models.CharField(max_length=128)),
                ('user_id', models.IntegerField()),
                ('driver_id', models.IntegerField(null=True)),
                ('requested', models.DateTimeField(auto_now_add=True)),
                ('assigned', models.DateTimeField(null=True)),
                ('canceled', models.DateTimeField(null=True)),
            ],
        ),
    ]
